version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  api:
    build: ./api
    container_name: flowbit-api
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app
    working_dir: /app
    command: npm run dev
    depends_on:
      - mongo

  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Asia/Kolkata
    restart: always

volumes:
  mongo-data:
